In [2]:
import numpy as np
from itertools import product


In [2]:
cell_one = [_ for _ in range(1,4)]
cell_1t9 = []
for i in range(3):
    ma_list = []
    for j in cell_one:
        ma_list.append(j + 3*i )
    cell_1t9.append(ma_list)

ma_mat = np.array(cell_1t9)
print(ma_mat)



[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
# x좌표가   xmin x max
# y좌표가 ymin ymax

cells = np.zeros((3, 3))
cells

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [34]:
len(cells)

3

In [12]:
updated_cells = np.zeros((cells.shape[0], cells.shape[1]))
updated_cells

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
for row, col in np.ndindex(ma_mat.shape):
    print(row, col)
    # if row == len()

0 0
0 1
0 2
1 0
1 1
1 2
2 0
2 1
2 2


In [39]:
cell_one = [_ for _ in range(1,4)]
cell_1t9 = []
for i in range(3):
    ma_list = []
    for j in cell_one:
        ma_list.append(j + 3*i )
    cell_1t9.append(ma_list)

ma_mat = np.array(cell_1t9)
print(ma_mat)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [55]:
ma_mat[-1:3, 1:3]

array([[8, 9]])

In [44]:
ma_mat[-1:2, -1:2]

array([], shape=(0, 0), dtype=int32)

In [42]:

for row, col in np.ndindex(ma_mat.shape):
    # print(ma_mat[row, col])
    # xmin ymin (0, 0)
    if (row == 0) and (col == 0):
        print(f'xmin, ymin : {ma_mat[row, col]}')
    # xmax, ymax (2, 2)
    elif (row == (len(ma_mat) - 1)) and (col == (len(ma_mat[0]) - 1)):
        print(f'xmax, ymax : {ma_mat[row, col]}')
    # xmin ymax (0, 2)
    elif (row == 0) and (col == (len(ma_mat[0]) - 1)):
        print(f'xmin, ymax : {ma_mat[row, col]}')
    # xmax ymin (2, 0)
    elif (row == (len(ma_mat) - 1)) and (col == 0):
        print(f'xmax, ymin : {ma_mat[row, col]}')
    # xmin
    elif (row == 0):
        print(f'xmin : {ma_mat[row, col]}')
    # xmax
    elif (row == (len(ma_mat) - 1)):
        print(f'xmax : {ma_mat[row, col]}')
    # ymin
    elif (col == 0):
        print(f'ymin : {ma_mat[row, col]}')
    # ymax
    elif (col == (len(ma_mat) - 1)):
        print(f'ymin : {ma_mat[row, col]}')
    else:
        print(f'else : {ma_mat[row, col]}')

xmin, ymin : 1
xmin : 2
xmin, ymax : 3
ymin : 4
else : 5
ymin : 6
xmax, ymin : 7
xmax : 8
xmax, ymax : 9


In [45]:
da_listo = []
da_listo.append((1, 2))
da_listo

[(1, 2)]

In [56]:
ma_mat2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [61]:
list_a = ['a', 'b']
list_b = ['A', 'B']
list_c = [list_a, list_b]
list_c
list(product(*list_c))

[('a', 'A'), ('a', 'B'), ('b', 'A'), ('b', 'B')]

In [74]:
ma_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [76]:
ma_mat[[0,0], [2, 0]]

array([3, 1])

In [82]:
ma_mat2 = np.zeros((5,5))
row, col = 0, 0
ma_mat2[row, col+1] + ma_mat2[row+1, col] + ma_mat2[row+1,col+1]

0.0

In [93]:
ma_mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [98]:
row, col = 0, 1
np.sum(ma_mat[row-1:row+2, col-1:col+2] - ma_mat[row, col])

0

In [102]:
row, col = 0, 1
np.sum(ma_mat[row+1:row+2, col+1])

6

In [133]:
row, col = 0, 1
print(ma_mat[row-1, col-1:col+2])
print(ma_mat[row:row+2, col-1:col+2])
np.sum(ma_mat[row:row+2, col-1:col+2]) - ma_mat[row, col]

[7 8 9]
[[1 2 3]
 [4 5 6]]


19

In [137]:
row, col = 2, 1

oppositor = len(ma_mat) - 1 
print(ma_mat[row-1:row+1, col-1:col+2])
print(ma_mat[row-(len(ma_mat)-1), col-1:col+2])

[[4 5 6]
 [7 8 9]]
[1 2 3]


In [141]:
row, col = 1, 0
print(ma_mat[row-1:row+2, col-1])
print(ma_mat[row-1:row+2, col:col+2])

[3 6 9]
[[1 2]
 [4 5]
 [7 8]]


In [143]:
row, col = 1, 2
print(ma_mat[row-1:row+2, col-1:col+2])
print(ma_mat[row-1:row+2, col-(len(ma_mat[0])-1)])

[[2 3]
 [5 6]
 [8 9]]
[1 4 7]


In [145]:
row, col = 1, 1
row_m, row_max, col_m, col_max = 0, (len(ma_mat) - 1), 0, (len(ma_mat[0]) - 1)
if (row == row_m) and (col == col_m):
        # print(f'xmin, ymin : {ma_mat[row, col]}')
        # xmin_ymin_list.append((row, col))
    alive = ma_mat[row_m, col_m+1] + ma_mat[row_m+1, col_m] + ma_mat[row_m+1, col_m+1] + ma_mat[row_max, col_m] + \
        ma_mat[row_max, col_m+1] + ma_mat[row_m, col_max] + ma_mat[row_m+1, col_max] + ma_mat[row_max, col_max]

# xmax, ymax (2, 2)
elif (row == row_max) and (col == col_max):
    # print(f'xmax, ymax : {ma_mat[row, col]}')
    # xmax_ymax_list.append((row, col))
    alive = ma_mat[row_max, col_max-1] + ma_mat[row_max-1, col_max] + ma_mat[row_max-1, col_max-1] + ma_mat[row_m, col_max] + \
        ma_mat[row_m, col_max-1] + ma_mat[row_max, col_m] + ma_mat[row_max-1, col_m] + ma_mat[row_m, col_m]
# xmin ymax (0, 2)
elif (row == row_m) and (col == col_max):
    # print(f'xmin, ymax : {ma_mat[row, col]}')
    # xmin_ymax_list.append((row, col))
    alive = ma_mat[row_m, col_max-1] + ma_mat[row_m+1, col_max] + ma_mat[row_m+1, col_max-1] + ma_mat[row_max, col_max] + \
        ma_mat[row_max, col_max-1] + ma_mat[row_m, col_m] + ma_mat[row_m+1, col_m] + ma_mat[row_max, col_m]
# xmax ymin (2, 0)
elif (row == row_max) and (col == col_m):
    # print(f'xmax, ymin : {ma_mat[row, col]}')
    # xmax_ymin_list.append((row, col))
    alive = ma_mat[row_max, col_m+1] + ma_mat[row_max-1, col_m] + ma_mat[row_max-1, col_m+1] + ma_mat[row_m, col_m] + \
        ma_mat[row_m, col_m+1] + ma_mat[row_max, col_max] + ma_mat[row_max-1, col_max] + ma_mat[row_m, col_max]
elif (row == row_m):
    # print(f'xmin : {ma_mat2[row, col]}')
    # xmin_list.append((row, col))
    alive = np.sum(ma_mat[row:row+2, col-1:col+2]) - ma_mat[row, col] + np.sum(ma_mat[row-1, col-1:col+2])
# xmax
elif (row == row_max):
    # print(f'xmax : {ma_mat2[row, col]}')
    # xmax_list.append((row, col))
    alive = np.sum(ma_mat[row-1:row+1, col-1:col+2]) - ma_mat[row, col] + np.sum(ma_mat[row-(len(ma_mat)-1), col-1:col+2])
# ymin
elif (col == col_m):
    # print(f'ymin : {ma_mat2[row, col]}')
    # ymin_list.append((row, col))
    alive = np.sum(ma_mat[row-1:row+2, col:col+2]) - ma_mat[row, col] + np.sum(ma_mat[row-1:row+2, col-1])
# ymax
elif (col == col_max):
    # print(f'ymin : {ma_mat2[row, col]}')
    # ymax_list.append((row, col))
    alive = np.sum(ma_mat[row-1:row+2, col-1:col+2]) - ma_mat[row, col] + np.sum(ma_mat[row-1:row+2, col-(len(ma_mat[0])-1)])
else:
    # print(f'else : {ma_mat2[row, col]}')
    # the_rest_list.append((row, col))
    alive = np.sum(ma_mat[row-1:row+2, col-1:col+2]) - ma_mat[row, col]

print(alive)

40


In [86]:
ma_mat2 = np.zeros((5,5))
row_max, col_max = (len(ma_mat2) - 1), (len(ma_mat2[0]) - 1)
col_max-1

3

In [ ]:
#original
mat_mat2 = np.zeros((5,5))
xmin_ymin_list = []
xmax_ymax_list = []
xmin_ymax_list = []
xmax_ymin_list = []
xmin_list = []
xmax_list = []
ymin_list = []
ymax_list = []
the_rest_list = []

row_m, row_max, col_m, col_max = 0, (len(ma_mat2) - 1), 0, (len(ma_mat2[0]) - 1)

for row, col in np.ndindex(ma_mat2.shape):
    # print(mat_mat2[row, col])

    # color = color_bg if cells[row, col] == 0 else color_alive_next
    
    # xmin ymin (0, 0)
    
    if (row == row_m) and (col == col_m):
        # print(f'xmin, ymin : {ma_mat2[row, col]}')
        # xmin_ymin_list.append((row, col))
        alive = ma_mat2[row_m, col_m+1] + ma_mat2[row_m+1, col_m] + ma_mat2[row_m+1, col_m+1] + ma_mat2[row_max, col_m] + \
            ma_mat2[row_max, col_m+1] + ma_mat2[row_m, col_max] + ma_mat2[row_m+1, col_max] + ma_mat2[row_max, col_max]

    # xmax, ymax (2, 2)
    elif (row == row_max) and (col == col_max):
        # print(f'xmax, ymax : {ma_mat2[row, col]}')
        # xmax_ymax_list.append((row, col))
        alive = ma_mat2[row_max, col_max-1] + ma_mat2[row_max-1, col_max] + ma_mat2[row_max-1, col_max-1] + ma_mat2[row_m, col_max] + \
            ma_mat2[row_m, col_max-1] + ma_mat2[row_max, col_m] + ma_mat2[row_max-1, col_m] + ma_mat2[row_m, col_m]
    # xmin ymax (0, 2)
    elif (row == row_m) and (col == col_max):
        # print(f'xmin, ymax : {ma_mat2[row, col]}')
        # xmin_ymax_list.append((row, col))
        alive = ma_mat2[row_m, col_max-1] + ma_mat2[row_m+1, col_max] + ma_mat2[row_m+1, col_max-1] + ma_mat2[row_max, col_max] + \
            ma_mat2[row_max, col_max-1] + ma_mat2[row_m, col_m] + ma_mat2[row_m+1, col_m] + ma_mat2[row_max, col_m]
    # xmax ymin (2, 0)
    elif (row == row_max) and (col == col_m):
        # print(f'xmax, ymin : {ma_mat2[row, col]}')
        # xmax_ymin_list.append((row, col))
        alive = ma_mat2[row_max, col_m+1] + ma_mat2[row_max-1, col_m] + ma_mat2[row_max-1, col_m+1] + ma_mat2[row_m, col_m] + \
            ma_mat2[row_m, col_m+1] + ma_mat2[row_max, col_max] + ma_mat2[row_max-1, col_max] + ma_mat2[row_m, col_max]
    # xmin
    elif (row == row_m):
    # print(f'xmin : {ma_mat2[row, col]}')
    # xmin_list.append((row, col))
        alive = np.sum(ma_mat2[row:row+2, col-1:col+2]) - ma_mat2[row, col] + np.sum(ma_mat2[row-1, col-1:col+2])
    # xmax
    elif (row == row_max):
        # print(f'xmax : {ma_mat2[row, col]}')
        # xmax_list.append((row, col))
        alive = np.sum(ma_mat2[row-1:row+1, col-1:col+2]) - ma_mat2[row, col] + np.sum(ma_mat2[row-(len(ma_mat2)-1), col-1:col+2])
    # ymin
    elif (col == col_m):
        # print(f'ymin : {ma_mat2[row, col]}')
        # ymin_list.append((row, col))
        alive = np.sum(ma_mat2[row-1:row+2, col:col+2]) - ma_mat2[row, col] + np.sum(ma_mat2[row-1:row+2, col-1])
    # ymax
    elif (col == col_max):
        # print(f'ymin : {ma_mat2[row, col]}')
        # ymax_list.append((row, col))
        alive = np.sum(ma_mat2[row-1:row+2, col-1:col+2]) - ma_mat2[row, col] + np.sum(ma_mat2[row-1:row+2, col-(len(ma_mat2[0])-1)])
    else:
        # print(f'else : {ma_mat2[row, col]}')
        # the_rest_list.append((row, col))
        alive = np.sum(ma_mat2[row-1:row+2, col-1:col+2]) - ma_mat2[row, col]


print(f'xmin, ymin : {xmin_ymin_list}')
print(f'xmax, ymax : {xmax_ymax_list}')
print(f'xmin, ymax : {xmin_ymax_list}')
print(f'xmax, ymin : {xmax_ymin_list}')
print(f'xmin : {xmin_list}')
print(f'xmax : {xmax_list}')
print(f'ymin : {ymin_list}')
print(f'fmax : {ymax_list}')
print(f'the rests: {the_rest_list}')


In [66]:
ma_mat3 = np.zeros((5,5))
xmin, xmax, ymin, ymax = 0, (len(ma_mat3) - 1), 0, (len(ma_mat3[0]) - 1)

two_min_max_list = [[xmin, xmax], [ymin, ymax]]
tmm_comb_list = list(product(*two_min_max_list) )
one_min_max_list = [xmin, xmax, ymin, ymax]
tmm_comb_list


[(0, 0), (0, 4), (4, 0), (4, 4)]

In [64]:
if (0, 0) in tmm_comb_list:
    print('yes')

yes


In [67]:
if (1, 0) in one_min_max_list:
    print('yes')

In [70]:
# TRIAL
ma_mat3 = np.zeros((5,5))
xmin, xmax, ymin, ymax = 0, (len(ma_mat3) - 1), 0, (len(ma_mat3[0]) - 1)

two_min_max_list = [[xmin, xmax], [ymin, ymax]]
tmm_comb_list = list(product(*two_min_max_list) )

tmm_collector_list = []
xmin = []
xmax = []
ymin = []
ymax = []
the_rest = []





for row, col in np.ndindex(ma_mat3.shape):
    # print(ma_mat[row, col])

    # color = color_bg if cells[row, col] == 0 else color_alive_next
    
    # xmin ymin (0, 0)
    if (row, col) in tmm_comb_list :
        tmm_collector_list.append((row, col))
        
        # alive = np.sum(ma_mat3[])
    # xmin
    elif (row == 0):
        # print(f'xmin : {ma_mat[row, col]}')
        xmin.append((row, col))
    # xmax
    elif (row == (len(ma_mat3) - 1)):
        # print(f'xmax : {ma_mat[row, col]}')
        xmax.append((row, col))
    # ymin
    elif (col == 0):
        # print(f'ymin : {ma_mat[row, col]}')
        ymin.append((row, col))
    # ymax
    elif (col == (len(ma_mat3) - 1)):
        # print(f'ymin : {ma_mat[row, col]}')
        ymax.append((row, col))
    else:
        # print(f'else : {ma_mat[row, col]}')
        the_rest.append((row, col))

print(f'two min max : {tmm_collector_list}')
print(f'xmin : {xmin}')
print(f'xmax : {xmax}')
print(f'ymin : {ymin}')
print(f'fmax : {ymax}')
print(f'the rests: {the_rest}')


two min max : [(0, 0), (0, 4), (4, 0), (4, 4)]
xmin : [(0, 1), (0, 2), (0, 3)]
xmax : [(4, 1), (4, 2), (4, 3)]
ymin : [(1, 0), (2, 0), (3, 0)]
fmax : [(1, 4), (2, 4), (3, 4)]
the rests: [(1, 1), (1, 2), (1, 3), (2, 1), (2, 2), (2, 3), (3, 1), (3, 2), (3, 3)]


In [ ]:
for row, col in np.ndindex(ma_mat.shape):
    if row-1 < 1 or col < -1 :
        pass



In [3]:

ma_list = [_ for _ in range(10)]
print(ma_list[9:0])

# print(len)

[]


In [6]:
len(ma_mat[0])

3

In [8]:
ma_mat[0][2]

3

In [4]:
np.zeros((60, 80))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [1]:
np.zeros((2,2,2))

NameError: name 'np' is not defined

In [13]:
import pygame
screen=pygame.display.set_mode([640, 480])
screen.fill([255, 255, 255])
red=255
blue=0
green=0
left=50 
top=50
width=90
height=90
filled=0
pygame.draw.rect(screen, [red, blue, green], [left, top, width, height], filled)
pygame.display.flip()
running=True
while running:
    for event in pygame.event.get():
        if event.type==pygame.QUIT:
            running=False
pygame.quit()

In [3]:

np.zeros((4, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [5]:
color_alive_next_list=[(250, 250, 110), (196, 236, 116), (146, 220, 126), (100, 201, 135), (57, 180, 142)]
color_alive_next_list[0]

TypeError: list indices must be integers or slices, not float

In [7]:
1%5

1